/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doctor.view;

import Doctor.controller.TableSearchHandler;
import Doctor.view.DoctorMenu;
import Doctor.model.viewAppointmentHistory;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Kingston Teoh
 */
public class DoctorAppointmentHistory extends javax.swing.JFrame {
        private viewAppointmentHistory viewappointmenthistory;
        private TableRowSorter<DefaultTableModel> sorter;
        private TableSearchHandler searchHandler;
        private DefaultTableModel model;        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorAppointmentHistory.class.getName());

    /**
     * Creates new form DoctorAppointmentHistory
     */
    public DoctorAppointmentHistory() {
        initComponents();
        setupTable();
        loadAppointments();
        searchHandler = new TableSearchHandler(AppointmentHistoryTable);
    }
    private void setupTable() {
        String[] cols = {"Appointment ID", "Date of Appointment", "Status", "Doctor ID", "Doctor Name", 
                     "Customer ID", "Customer Name", "Feedback", "Subject", "Context"};
        int[] w = {120, 100, 120, 150, 150, 100, 150, 200, 150, 250};
    
        model = new DefaultTableModel(cols, 0) {
            public boolean isCellEditable(int r, int c) { return c != 0; }
        };
    
        AppointmentHistoryTable.setModel(model);
        AppointmentHistoryTable.setAutoCreateRowSorter(true);
    
        viewappointmenthistory = new viewAppointmentHistory(model);
        sorter = viewappointmenthistory.getSorter();
        AppointmentHistoryTable.setRowSorter(sorter);
    
        TableColumnModel cm = AppointmentHistoryTable.getColumnModel();
        for (int i = 0; i < w.length; i++) {
            cm.getColumn(i).setPreferredWidth(w[i]);
        }

        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);
    // Center align specific columns if needed
        cm.getColumn(0).setCellRenderer(center); // Appointment ID
        cm.getColumn(2).setCellRenderer(center); // Status
        cm.getColumn(3).setCellRenderer(center); // Doctor ID
        cm.getColumn(5).setCellRenderer(center); // Customer ID
    
        AppointmentHistoryTable.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);

        }
    
    private void loadAppointments()
    {
        String filePath ="src\\database\\appointments.txt";
        viewappointmenthistory.loadFromTxt(filePath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AppointmentHistoryTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AppointmentSearchtxt = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AppointmentHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Status", "Customer ID", "Customer Name", "Doctor ID", "Doctor Name", "Feedback", "Subject", "Context"
            }
        ));
        jScrollPane2.setViewportView(AppointmentHistoryTable);

        jLabel3.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel3.setText("Appointment History");

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setText("Search:");

        AppointmentSearchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentSearchtxtActionPerformed(evt);
            }
        });
        AppointmentSearchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppointmentSearchtxtKeyReleased(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AppointmentSearchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(backbtn)
                                .addGap(226, 226, 226)
                                .addComponent(jLabel3)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(backbtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(AppointmentSearchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.dispose(); // Close current frame
        DoctorMenu obj = new DoctorMenu();
        obj.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_backbtnActionPerformed

    private void AppointmentSearchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentSearchtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppointmentSearchtxtActionPerformed

    private void AppointmentSearchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppointmentSearchtxtKeyReleased
        String query = AppointmentSearchtxt.getText();
        searchHandler.filterTable(query);       // TODO add your handling code here:
    }//GEN-LAST:event_AppointmentSearchtxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DoctorAppointmentHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AppointmentHistoryTable;
    private javax.swing.JTextField AppointmentSearchtxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
