/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doctor.view;

import Doctor.controller.DoctorCtrl;
import Doctor.model.Doctor;
import User.UserProfile;

/**
 *
 * @author Kingston Teoh
 */
public class DoctorMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorMenu.class.getName());
    
    private DoctorCtrl ctrl;
    private Doctor currentDoctor;
    
    /**
     * Creates new form DoctorMenu
     */
    public DoctorMenu(DoctorCtrl ctrl) {
        initComponents();
        this.ctrl = ctrl;
        currentDoctor = ctrl.getCurrentDoctor();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Appointmentbtn = new javax.swing.JButton();
        Chargesbtn = new javax.swing.JButton();
        Historybtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Exitbtn = new javax.swing.JButton();
        Feedbackbtn = new javax.swing.JButton();
        EditProfilebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Appointmentbtn.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        Appointmentbtn.setText("Appointment");
        Appointmentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentbtnActionPerformed(evt);
            }
        });

        Chargesbtn.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        Chargesbtn.setText("Charges");
        Chargesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargesbtnActionPerformed(evt);
            }
        });

        Historybtn.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        Historybtn.setText("History");
        Historybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorybtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setText("Welcome Doctor !");

        Exitbtn.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        Exitbtn.setText("Exit");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        Feedbackbtn.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        Feedbackbtn.setText("Feedback");
        Feedbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackbtnActionPerformed(evt);
            }
        });

        EditProfilebtn.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        EditProfilebtn.setText("Edit Profile");
        EditProfilebtn.setActionCommand("");
        EditProfilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfilebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EditProfilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Appointmentbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Chargesbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Historybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Feedbackbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(Appointmentbtn)
                .addGap(32, 32, 32)
                .addComponent(Chargesbtn)
                .addGap(37, 37, 37)
                .addComponent(Feedbackbtn)
                .addGap(38, 38, 38)
                .addComponent(Historybtn)
                .addGap(37, 37, 37)
                .addComponent(EditProfilebtn)
                .addGap(40, 40, 40)
                .addComponent(Exitbtn)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AppointmentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentbtnActionPerformed
        this.setVisible(false);
        DoctorAppointment obj = new DoctorAppointment(ctrl);
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AppointmentbtnActionPerformed

    private void ChargesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargesbtnActionPerformed
        this.setVisible(false);
        DoctorCharges obj1 = new DoctorCharges(ctrl);
        obj1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ChargesbtnActionPerformed

    private void HistorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorybtnActionPerformed
        this.setVisible(false);
        DoctorAppointmentHistory obj2 = new DoctorAppointmentHistory(ctrl);
        obj2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_HistorybtnActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void FeedbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackbtnActionPerformed
        this.setVisible(false);
        DoctorFeedback obj3 = new DoctorFeedback(ctrl);
        obj3.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_FeedbackbtnActionPerformed

    private void EditProfilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfilebtnActionPerformed
        // TODO add your handling code here:
        UserProfile profile = new UserProfile();
        profile.setCurrentUser(currentDoctor);
        profile.setNavigationCallback(() -> {
            this.setVisible(true); // Show doctor dashboard again
        });
        this.setVisible(false);
        profile.setVisible(true);
    }//GEN-LAST:event_EditProfilebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appointmentbtn;
    private javax.swing.JButton Chargesbtn;
    private javax.swing.JButton EditProfilebtn;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Feedbackbtn;
    private javax.swing.JButton Historybtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
